@startuml
!include .\\BookingModel.puml
!include .\\CityModel.puml
!include .\\ContryModel.puml
!include .\\ErrorViewModel.puml
!include .\\LandlordModel.puml
!include .\\ListningModel.puml
!include .\\RenterModel.puml
!include .\\UserModel.puml
@enduml
