@startuml
class ListningModel {
    + ListningId : int <<get>> <<set>>
    + ListningName : string <<get>> <<set>>
    + ListningDescription : string? <<get>> <<set>>
    + NoOfBeds : int <<get>> <<set>>
    + SquareMeter : int <<get>> <<set>>
    + Rating : float <<get>> <<set>>
    + ListningAddress : string <<get>> <<set>>
    + ListningPrice : double <<get>> <<set>>
    + ListningImageURL : string? <<get>> <<set>>
    + <<virtual>> bookings : List<BookingModel>? <<get>> <<set>>
}
ListningModel o-> "user" UserModel
ListningModel --> "fromDate" DateOnly
ListningModel --> "toDate" DateOnly
@enduml
